Hello microverse setup
Fernando426/Hello-world pull request #2
Opened 2023-04-27 15:41 UTC by Fernando426

- The broken link to the license was fixed
- Removed unnecessary comments from the readme file
- Removed unnecessary lines from the linter file, which are for checking JavaScript code

2023-04-27 15:46 UTC, Fernando426 commented
This is the link to the previous pull request:   https://github.com/Fernando426/Hello-world/pull/1

2023-04-27 16:33 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @Fernando426 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 16:33 UTC, abdulhamiid commented on README.md
> +- [📝 License](#license)
- [ ] As requested by the previous reviewer, it is important that all main headers from the [README template](https://github.com/microverseinc/readme-template) are present in our repo to ensure that we have a well-descriptive readme file. 👍. The only optional section is the `FAQ`.

- [ ] Kindly check all the main headers of the README template below 👇 

![image](https://user-images.githubusercontent.com/78251927/234923748-f1e2d9fc-d17a-4a5b-b1a7-525cc0366086.png)

- [ ] Your readme 👇 

![image](https://user-images.githubusercontent.com/78251927/234925816-d18cdb95-4919-40c9-887e-728dccf9574e.png)

Kindly add the section **Future Features**, including 1-3 potential features to be added. 👍 🛠

2023-04-27 16:33 UTC, abdulhamiid commented on README.md
> +- LinkedIn: [Fernando Montes](https://www.linkedin.com/in/fernando-jose-montes-linares-523822270/?originalSubdomain=ve)
[OPTIONAL] - The link to your `Twitter` profile is broken, kindly fix it by adding the correct URL. 🛠

![image](https://user-images.githubusercontent.com/78251927/234928716-2e9a6646-e882-44b1-ae72-0b678bd1db33.png)

Let's avoid broken links in our readme file for a professional repository. 🤗👍

2023-04-27 18:15 UTC, Fernando426 commented
Hello, thanks for the review, about the instruction not to open a new pull
request, I have a question, should I just make the corrections and make a
new push?
 That way it will already be reflected in the current pull request?
Or do I need any additional steps?

El jue, 27 abr 2023 a la(s) 12:34, Adio Abdulhamid ***@***.***)
escribió:

> ***@***.**** requested changes on this pull request.
> Status: Required Changes ♻️
>
> Hi @Fernando426 <https://github.com/Fernando426> 👋,
>
> Great work on making the changes requested by the previous reviewer 👏
> You've done well implementing some of the requested changes, I really
> appreciate the effort you put in! but there are still some which haven't
> been addressed yet.
>
> [image: almost-there]
> <https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif>
> Highlights 🌟
>
>    - ✔️ Descriptions are descriptive
>    - ✔️ Linters checks are passing
>    - ✔️ Use GitHub Flow
>
> Required Changes ♻️
>
> *Please kindly check the comments under the review.*
> Optional suggestions 🤷‍♂️
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you take them into
> account as they can make your code better.*
>
> Cheers, and Happy coding!👏👏👏
> Important Notes 📝
>
>    - Feel free to leave any questions or comments in the PR thread if
>    something is not 100% clear.
>    - Please, remember to tag me in your question so I can receive the
>    notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/Fernando426/Hello-world/pull/2#discussion_r1179431026>
> :
>
> > +# 📗 Table of Contents
> +
> +- [📖 About the Project](#about-project)
> +  - [🛠 Built With](#built-with)
> +  - [Key Features](#key-features)
> +- [💻 Getting Started](#getting-started)
> +- [👥 Authors](#authors)
> +- [🤝 Contributing](#contributing)
> +- [⭐️ Show your support](#support)
> +- [🙏 Acknowledgements](#acknowledgements)
> +- [📝 License](#license)
>
>
>    -
>
>    As requested by the previous reviewer, it is important that all main
>    headers from the README template
>    <https://github.com/microverseinc/readme-template> are present in our
>    repo to ensure that we have a well-descriptive readme file. 👍. The
>    only optional section is the FAQ.
>    -
>
>    Kindly check all the main headers of the README template below 👇
>
> [image: image]
> <https://user-images.githubusercontent.com/78251927/234923748-f1e2d9fc-d17a-4a5b-b1a7-525cc0366086.png>
>
>    - Your readme 👇
>
> [image: image]
> <https://user-images.githubusercontent.com/78251927/234925816-d18cdb95-4919-40c9-887e-728dccf9574e.png>
>
> Kindly add the section *Future Features*, including 1-3 potential
> features to be added. 👍 🛠
> ------------------------------
>
> In README.md
> <https://github.com/Fernando426/Hello-world/pull/2#discussion_r1179431541>
> :
>
> > +- GitHub: ***@***.***(https://github.com/Fernando426)
> +- Twitter: ***@***.***(https://twitter.com/twitterhandle)
> +- LinkedIn: [Fernando Montes](https://www.linkedin.com/in/fernando-jose-montes-linares-523822270/?originalSubdomain=ve)
>
> [OPTIONAL] - The link to your Twitter profile is broken, kindly fix it by
> adding the correct URL. 🛠
>
> [image: image]
> <https://user-images.githubusercontent.com/78251927/234928716-2e9a6646-e882-44b1-ae72-0b678bd1db33.png>
>
> Let's avoid broken links in our readme file for a professional repository.
> 🤗👍
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Fernando426/Hello-world/pull/2#pullrequestreview-1404466287>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUFPYSWFI6IEKTCQB7ZEWZTXDKNXZANCNFSM6AAAAAAXOBOQHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-28 14:59 UTC, ABDULALI3468 approved these changes
Hi @Fernando426 , 👍 

# APPROVED 💯 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>

## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 16:11 UTC, merged